name: ElderlyCompanion
options:
  bundleIdPrefix: com.futureselflabs
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

packages:
  LiveKit:
    url: https://github.com/livekit/client-sdk-swift
    from: "2.0.0"

settings:
  base:
    SWIFT_VERSION: "5.10"
    DEVELOPMENT_TEAM: ""

targets:
  ElderlyCompanion:
    type: application
    platform: iOS
    sources:
      - ElderlyCompanion
    entitlements:
      path: ElderlyCompanion/ElderlyCompanion.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
    settings:
      base:
        INFOPLIST_FILE: ElderlyCompanion/App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.futureselflabs.elderlycompanion
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: "YES"
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_ENTITLEMENTS: ElderlyCompanion/ElderlyCompanion.entitlements
    dependencies:
      - package: LiveKit
        product: LiveKit
    info:
      path: ElderlyCompanion/App/Info.plist
      properties:
        CFBundleDisplayName: Noah
        CFBundleName: ElderlyCompanion
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSCalendarsUsageDescription: "Noah uses your calendar to help manage appointments and send you timely reminders."
        NSCalendarsFullAccessUsageDescription: "Noah uses your calendar to help manage appointments and send you timely reminders."
        NSMicrophoneUsageDescription: "Noah needs access to your microphone so you can talk with your companion."
        NSContactsUsageDescription: "Noah can access your contacts to help manage your trusted circle."
        NSHealthShareUsageDescription: "Noah reads your health data to monitor your wellbeing and share important updates with your family circle."
        NSHealthUpdateUsageDescription: "Noah does not write health data, only reads it."
        UIBackgroundModes:
          - audio
          - voip
        ITSAppUsesNonExemptEncryption: false
